// This file was autogenerated by /Users/anhkiet/projects/freya/bundle/ruby/1.9.1/bundler/gems/mozdev-f23bc50b8b6e/lib/mozdev/../ext/ext_closure/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/Users/anhkiet/projects/scripted/play-area/p/code.js', ['freya.View'], ['freya.Mozmod']);
goog.addDependency('/Users/anhkiet/projects/scripted/play-area/p/lib/mozmod.js', ['freya.Mozmod'], []);
